### ISSUE TITLE
Split documentation into multiple files

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#464]
### The problem
Our README is exceedingly large. This is not ideal, as it makes it somewhat difficult to navigate (see #322). In addition, in Safari, the anchors don't work properly, which makes links to parts of the documentation unusable.

### Possible solution
We need to split the README into multiple files. At the very list, subsections of [Symbols and Functions](https://github.com/maxitg/SetReplace/#symbols-and-functions) should go into different files.

Likely, [WolframModel and WolframModelEvolutionObject](https://github.com/maxitg/SetReplace/#wolframmodel-and-wolframmodelevolutionobject) should be split into multiple files as well, probably one file per each property/option.

### Additional context
A significant downside is that all links will be broken. We will have to go through all open issues and documents (README, contributing, and the research documents), and fix all of the links. Of course, we cannot fix the external links (although they would not be entirely broken, they will just lead to the main documentation page).

**Comment by wawo9193** [comment]
Hi @maxitg, could I take this issue? Thank you

**Comment by maxitg** [comment]
@wawo9193, definitely! Thanks for your interest!

**Comment by wawo9193** [comment]
@maxitg Would a GitHub wiki with subsections be okay? Or is there another route that is preferred? Glad to help

**Comment by maxitg** [comment]
@wawo9193, we want it to be version controlled, so putting them in the "Documentation" directory makes the most sense.

**Comment by wawo9193** [comment]
@maxitg I split up the sections, but not 100% on the choice of sections if it would be preferred to have it broken up even more.
For the links I took all the links that went to header positions on the readme and added a relative file path. i.e. #state would be changed to Properties.md#state, so that when it is clicked it goes to that point on the page. Image paths were updated as well.
Of course this is just the first run through, so if you see anything that needs changing, please let me know.

**Comment by maxitg** [comment]
Thanks for helping out! I left comments in the pull request review.
