### ISSUE TITLE
WolframModel crashes mathematic even with small iteration numbers

### ISSUE THREAD

**Issue by Cloudmersive** [maxitg/SetReplace#660]
### The problem

Running Mathematica latest version on a 16 core x 64 GB PC.  When I run this command:

ResourceFunction[
 "WolframModel"][{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, 20, "FinalStatePlot"]

It freezes Mathematica for a long time, it does eventually return but this is way too slow.  The whole point of WolframModel should be to support very large numbers of iterations.  Need to make this code actually fast and efficient.

### Version

Latest

### Additional context

This is super broken - without being able to explore WolframModels with a large number of iterations, this is just demoware and cannot be used for any serious investigation

**Comment by maxitg** [comment]
It currently takes 48 seconds on my machine to generate the evolution object for this system:

```wl
In[] := WolframModel[{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, w}}, {{0, 0}, {0, 0}}, 20]
```
<img width="472" alt="image" src="https://user-images.githubusercontent.com/1479325/124311922-1c07fd00-db34-11eb-85c5-2b2640aa45a3.png">

The object has 218,562 events and there are 437,126 edges in the final state. Indeed, we do not have a way to plot graphs this large at the moment (not just in *SetReplace*, but also in Wolfram Language).

If you have ideas on how to make it faster, feel free to reopen this issue and comment on that.

PS. In order to use the latest version of *SetReplace*, you need to compile it from the source (or install a paclet generated by CI). `ResourceFunction["WolframModel"]` uses a version that is quite old. Also, please use the template when creating an issue (especially, `$SetReplaceGitSHA`, etc.).

**Comment by Cloudmersive** [comment]
@maxitg It would be really great if you guys could update ResourceFunction[...].  

I would also say that 400K edges is really not that many - the average videogame has tens of millions of triangles onscreen at any given moment.  

To make substantial progress in this area it really feels like basic functions like WolframModel will need to be rewritten in a more scalable programming language like C++ and then used from Python notebooks.
