### ISSUE TITLE
Version of SetReplace on ResourceFunction["WolframModel"] is out of date

### ISSUE THREAD

**Issue by Cloudmersive** [maxitg/SetReplace#661]
As described here: https://github.com/maxitg/SetReplace/issues/660

The version of SetReplace on ResourceFunction["WolframModel"] is old and out of date, and suffers from poor performance and scalability.  But this needs to be updated because this is how most people are actually using the WolframModel function.  Can you release a new drop to ResourceFunction please?

**Comment by maxitg** [comment]
Function Repository is not suited for packages, and *SetReplace* should not be used via function repository. The existence of `ResourceFunction["WolframModel"]` is a terrible hack. It's unfortunate that most people use the resource function (due to poor communication by the physics project), but the solution for those people is to switch to using *SetReplace* directly.

In fact, the new API for *SetReplace* that we are working on right now would not even be technically possible to implement via function repository.

Thus, the correct upgrade path is to go from using WFR to using *SetReplace* directly.
